version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://contacts_user:contacts_pass@db:5432/contacts_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: contacts_db
      POSTGRES_USER: contacts_user
      POSTGRES_PASSWORD: contacts_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U contacts_user -d contacts_db"]
      interval: 10s      # cada cuánto probar
      timeout: 5s        # tiempo máximo para que responda
      retries: 5         # cuántas veces intentar antes de marcar como "unhealthy"
      start_period: 5s   # tiempo inicial antes de empezar a chequear

volumes:
  postgres_data: